### ISSUE TITLE
Can't use "reload" command

### ISSUE THREAD

**Issue by mhbates** [linuxserver/docker-fail2ban#3]
When I attempt to reload Fail2Ban or a particular jail via `docker exec fail2ban fail2ban-client reload` or `reload <jail>`, I get errors like:

`[200]: ERROR   Failed during configuration: Have not found any log file for sshd jail`
`[206]: ERROR   Failed during configuration: No section: 'nextcloud-auth'`
`[212]: ERROR   Failed during configuration: No section: 'overseerr-auth'`

**Comment by nemchik** [comment]
I just tried and confirmed, I am seeing the same error. I'm not sure exactly why, but I'll experiment to see what I can figure out.

Until then I'd recommend restarting the entire container

**Comment by nemchik** [comment]
Just a small update on this:

`docker exec fail2ban fail2ban-client -c /config/fail2ban reload` does work.

Just some additional information (explaining what's going on):

- `fail2ban` by default looks for config files in `/etc/fail2ban`
- This image runs `fail2ban` with `-c /config/fail2ban` so it uses that folder for configs
- [SWAG](https://github.com/linuxserver/docker-swag) instead copies your files from `/config/fail2ban` to `/etc/fail2ban` but this means reloading isn't very useful because your changes are only copied when the container is started (or restarted)

So I'm not sure if there will be a decent compromise with this. Restarting the image is probably the safest and easiest option.

**Comment by nemchik** [comment]
```
docker exec fail2ban fail2ban-client reload
```

should work after pulling `1.0.2-r0-ls11`
